server {
    server_name reactfreejoy.top www.reactfreejoy.top;

    root /var/www/React-FJ/apps/site/dist;
    index index.html;

    location ^~ /assets/ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        add_header Surrogate-Control "no-store" always;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/reactfreejoy.top/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/reactfreejoy.top/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.reactfreejoy.top) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = reactfreejoy.top) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name reactfreejoy.top www.reactfreejoy.top;
    return 404; # managed by Certbot
}
